blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/shahinabdi/sway-configs-arch/discussions
    about: Ask questions or discuss ideas that aren't a bug or feature request.
